version: "2"

services:
  nginx:
    image: nginx
    container_name: "nginx-dev"
    ports:
      - "8080:80"
    volumes:
      - ./src:/src
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  php:
    build: ./php
    container_name: "laravel-dev"
    volumes:
      - ./src:/src
  mysql:
    image: mysql
    container_name: "mysql-dev"
    restart: always
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - 13306:3306
  redis:
    image: redis:alpine
    container_name: "radis-dev"
    ports:
      - 16379:6379
